name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BUCKET_NAME: "node-express-actions-artifact"
  AWS_REGION: "ap-south-1"
  GITHUB_REF: "main"

jobs:
  build:
    runs-on: ubuntu-latest
    #permission can be added at job level or workflow level
    permissions:
      id-token: write
      contents: read #required for actions/checkout
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::754345194439:role/GitHub-actions-role
          role-session-name: Github-Actions-Role
          aws-region: ${{ env.AWS_REGION }}

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Extract commit hash
        shell: bash
        run: echo "##[set-output name=commit_hash;]$(echo "$GITHUB_SHA")"
        id: extract_hash

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - run: npm ci
      - run: npm run build
      - run: npm run lint

      - name: Make Artifact directory
        run: mkdir -p ./artifacts

      # Copy build directory to S3
      - name: Copy build to S3
        run: |
          zip -r ./artifacts/project.zip . -x node_modules/**\* .git/**\* dist/**\* dist/**\*          
          aws s3 sync  ${GITHUB_WORKSPACE}/artifacts s3://${{ env.BUCKET_NAME }}/${{ steps.extract_branch.outputs.branch }}/latest
